project_name: client

env:
- GO111MODULE=on
- COSIGN_EXPERIMENTAL=true

before:
  hooks:
    - go mod tidy
    - go mod vendor

builds:
  -
    binary: client-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    main: ./cmd/client
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - s390x
      - ppc64le
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: ppc64le
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: ppc64le
    ldflags:
      - "-X github.com/uor-framework/client/cli.version={{ .Tag }}"
      - "-X github.com/uor-framework/client/cli.commit={{ .ShortCommit }}"
      - "-X github.com/uor-framework/client/cli.buildDate={{ .Date }}"
    env:
      - CGO_ENABLED=0
  
signs:
- id: client-keyless
  signature: "${artifact}.sig"
  certificate: "${artifact}.pem"
  env:
  - COSIGN_EXPERIMENTAL=1
  cmd: cosign
  args:
    - sign-blob
    - "--output-certificate=${certificate}"
    - "--output-signature=${signature}"
    - "${artifact}"
  artifacts: binary
  output: true

archives:
  - format: binary
    name_template: "{{ .Binary }}"
    allow_different_binary_count: true
    replacements:
      linux: Linux
      darwin: Darwin
      windows: Windows
      amd64: x86_64

sboms:
- artifacts: binary

dockers:
  - image_templates: 
      - ghcr.io/usrbinkat/{{ .ProjectName }}:{{ .Tag }}-amd64
    dockerfile: Containerfile
    use: buildx
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/usrbinkat/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/usrbinkat/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Tag }}
    - --label=org.opencontainers.image.created={{ .Date }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=APACHE2.0
docker_manifests:
  - name_template: ghcr.io/usrbinkat/client:{{ .Tag }}
    image_templates:
      - ghcr.io/usrbinkat/client:{{ .Tag }}-amd64
  - name_template: ghcr.io/usrbinkat/client:latest
    image_templates:
      - ghcr.io/usrbinkat/client:{{ .Tag }}-amd64

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - go mod tidy

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

release:

  prerelease: allow
  draft: true
  github:
    owner: usrbinkat
    name: client

  header: |

    ## UOR Client ({{ .Version }})

  footer: |

    ### Thanks to all contributors!

  name_template: "{{.ProjectName}}-{{ .Tag }}"
